### ISSUE TITLE
Parallel download for Elasticsearch and Kibana

### ISSUE THREAD

**Issue by renshuki** [renshuki/elasticsearch-bootstrap#2]
- Put curl function in the background `&`
 - Loop and compare the hash (sha512) of the file to know when the download is complete
 - Prompt the user

Thanks to @TomonoriSoejima for the idea.

**Comment by renshuki** [comment]
I resolved the parallel download using `xargs` and `wget` with 2 concurrent process.

https://github.com/renshuki/elasticsearch-bootstrap/blob/822a6cb6b94d397ae63424adcb1948eb91adadb0/lib/functions.sh#L125

Should be working as expected.

**Comment by TomonoriSoejima** [comment]
nice one!
I once used `parallels` in the past as well for a similar case.
https://www.freecodecamp.org/news/how-to-supercharge-your-bash-workflows-with-gnu-parallel-53aab0aea141/

**Comment by renshuki** [comment]
Thanks @TomonoriSoejima for the share, I indeed saw some stuff around `parallel` however I was looking for something more "native". That's why I went with `xargs` instead.
